### PR TITLE
added Whisk button and script tag

### PR DESCRIPTION
**Pull request by whitney227**
add this to JS...probably leave product array empty?

<script>
  whisk.queue.push(function() {
    whisk.listeners.addClickListener(
      'whisk-shop-products',
      'shoppingList.addProductsToBasket', {
        products: ['Coffee', 'Ice Cream', 'Lemon']
      }
    );
  });
</script>

### CODE REVIEW

**Review by EthanBonsignori — COMMENTED** [review]
Im on my phone so its hard to tell but why is there a new html file?

**Review by EthanBonsignori — CHANGES_REQUESTED** [review]
Remove extra Html file

**Comment by whitney227** [comment]
I deleted the file and have changed the dropdown in the navbar.

**Review by EthanBonsignori — APPROVED** [review]
Ok im home now and it let me remove the file

**Pull request merged**
